### ISSUE TITLE
removing all references to dev mode in the code and docs

### ISSUE THREAD

**Issue by mmerce** [bigmlcom/bigml-java#16]

**Comment by javinp** [comment]
We keep signatures with devMode in BigMLClient for backward compatibility.

**Comment by mmerce** [comment]
It's fine to keep it for a while, changing the value internally to false, and changing all docs and examples to remove the use of devMode. Also adding a note saying that the argument is marked to be deprecated. But then, in next major version, the parameter should be removed.
