### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by jaor** [bigmlcom/bigml-java#6]
There are a couple of documentation problems:
- In the comments of `org.bigml.binding.LocalPredictiveModel` there's an example that says:

``` java
  BigMLClient bigmlClient = new BigMLClient();
```

   it should be `BigMLClient.getInstance()`, i guess.
- In the docs, the example with the two-string argument's getInstance example is wrong:

``` java
   BigMLClient api = BigMLClient.getInstance("foo", "xxxxxxxxxxx");
```

that **does not** create a client using a username and an api key, but another thing involving a seed and an storage.  The correct invocation would be:

``` java
   BigMLClient api = BigMLClient.getInstance("foo", "xxxxxxxxxxx", false);
```

I actually think having a getInstance taking two strings that are not
username/apikey is very confusing (as demonstrated by the fact that
even our documentation get it wrong) and would change the interface.  But
if you don't agree, at the very least the docs should be updated.

(i'm assigning the bug to @leonhwang just because he's the last committer, please reassign as needed)

**Comment by leonhwang** [comment]
Thanks for pointing out the bugs.
I will correct them.
I also agree about taking two strings signature, but I see there is an existing one that takes two strings (see below), so it will be a problem.

public static BigMLClient getInstance(final String seed, final String storage)

**Comment by jaor** [comment]
yes, it's the existing one that makes things confusing... i was writing
tests and using that one by mistake, which compiles fine, but doesn't
work at runtime, of course, because it doesn't do what i thought it'd
do, but the error is not obvious.

i guess we could at least warn about it in the docs...
